export let sources = [
{src:"/assets/imgs/001.jpg",
checked:true},
{src:"/assets/imgs/002.jpg",
checked:true},
{src:"/assets/imgs/003.jpg",
checked:false},
{src:"/assets/imgs/004.jpg",
checked:false},
{src:"/assets/imgs/010.jpg",
checked:false},
{src:"/assets/imgs/011.jpg",
checked:false},
{src:"/assets/imgs/017.jpg",
checked:false},
{src:"/assets/imgs/021.jpg",
checked:false},
{src:"/assets/imgs/028.jpg",
checked:false},
{src:"/assets/imgs/033.jpg",
checked:false},
{src:"/assets/imgs/035.jpg",
checked:false},
{src:"/assets/imgs/040.jpg",
checked:false},
{src:"/assets/imgs/042.jpg",
checked:false},
// {src:"/assets/imgs/043.jpg",
// checked:false},
// {src:"/assets/imgs/045.jpg",
// checked:false},
// {src:"/assets/imgs/046.jpg",
// checked:false},
// {src:"/assets/imgs/047.jpg",
// checked:false},
// {src:"/assets/imgs/048.jpg",
// checked:false},
// {src:"/assets/imgs/050.jpg",
// checked:false},
// {src:"/assets/imgs/052.jpg",
// checked:false},
// {src:"/assets/imgs/053.jpg",
// checked:false},
// {src:"/assets/imgs/055.jpg",
// checked:false},
// {src:"/assets/imgs/059.jpg",
// checked:false},
// {src:"/assets/imgs/060.jpg",
// checked:false},
// {src:"/assets/imgs/063.jpg",
// checked:false},
// {src:"/assets/imgs/067.jpg",
// checked:false},
// {src:"/assets/imgs/068.jpg",
// checked:false},
// {src:"/assets/imgs/073.jpg",
// checked:false},
// {src:"/assets/imgs/076.jpg",
// checked:false},
// {src:"/assets/imgs/077.jpg",
// checked:false},
// {src:"/assets/imgs/081.jpg",
// checked:false},
// {src:"/assets/imgs/082.jpg",
// checked:false},
// {src:"/assets/imgs/083.jpg",
// checked:false},
// {src:"/assets/imgs/085.jpg",
// checked:false},
// {src:"/assets/imgs/087.jpg",
// checked:false},
// {src:"/assets/imgs/089.jpg",
// checked:false},
// {src:"/assets/imgs/090.jpg",
// checked:false},
// {src:"/assets/imgs/091.jpg",
// checked:false},
// {src:"/assets/imgs/093.jpg",
// checked:false},
// {src:"/assets/imgs/094.jpg",
// checked:false},
// {src:"/assets/imgs/095.jpg",
// checked:false},
// {src:"/assets/imgs/096.jpg",
// checked:false},
// {src:"/assets/imgs/097.jpg",
// checked:false},
// {src:"/assets/imgs/098.jpg",
// checked:false},
// {src:"/assets/imgs/099.jpg",
// checked:false},
// {src:"/assets/imgs/100.jpg",
// checked:false},
// {src:"/assets/imgs/101.jpg",
// checked:false},
// {src:"/assets/imgs/103.jpg",
// checked:false},
// {src:"/assets/imgs/107.jpg",
// checked:false},
// {src:"/assets/imgs/111.jpg",
// checked:false},
// {src:"/assets/imgs/112.jpg",
// checked:false},
// {src:"/assets/imgs/119.jpg",
// checked:false},
// {src:"/assets/imgs/125.jpg",
// checked:false},
// {src:"/assets/imgs/127.jpg",
// checked:false},
// {src:"/assets/imgs/129.jpg",
// checked:false},
// {src:"/assets/imgs/130.jpg",
// checked:false},
// {src:"/assets/imgs/133.jpg",
// checked:false},
// {src:"/assets/imgs/134.jpg",
// checked:false},
// {src:"/assets/imgs/137.jpg",
// checked:false},
// {src:"/assets/imgs/138.jpg",
// checked:false},
// {src:"/assets/imgs/139.jpg",
// checked:false},
// {src:"/assets/imgs/140.jpg",
// checked:false},
// {src:"/assets/imgs/141.jpg",
// checked:false},
// {src:"/assets/imgs/142.jpg",
// checked:false},
// {src:"/assets/imgs/143.jpg",
// checked:false},
// {src:"/assets/imgs/144.jpg",
// checked:false},
// {src:"/assets/imgs/145.jpg",
// checked:false},
// {src:"/assets/imgs/146.jpg",
// checked:false},
// {src:"/assets/imgs/147.jpg",
// checked:false},
// {src:"/assets/imgs/150.jpg",
// checked:false},
// {src:"/assets/imgs/152.jpg",
// checked:false},
// {src:"/assets/imgs/155.jpg",
// checked:false},
// {src:"/assets/imgs/157.jpg",
// checked:false},
// {src:"/assets/imgs/165.jpg",
// checked:false},
// {src:"/assets/imgs/171.jpg",
// checked:false},

]
